# Dockerfile
FROM node:20.10.0-alpine

# create destination directory
RUN mkdir -p /usr/src/QuicTube
WORKDIR /usr/src/QuicTube

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY . /usr/src/QuicTube/

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "npm", "run", "dev" ]
