version: 1.0.2
services:
    quic-tube.test:
        build:
            context: ./
            dockerfile: Dockerfile

        image: quic-tube-nuxt
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${NUXT_PORT:-3000}:3000'

        volumes:
            - '.:/usr/src/QuicTube/'
        networks:
            - quic-tube
networks:
  quic-tube:
        driver: bridge
